#### NUMPY Indexing and selection

In [1]:
import numpy as np

In [2]:
arr = np.arange(10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr[8]

8

In [5]:
arr[:5]

array([0, 1, 2, 3, 4])

In [6]:
arr[5:]

array([5, 6, 7, 8, 9])

In [7]:
 arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [8]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
## changes didn't happened so to save the changes to an array assign it to new variable - create new object
arr_3 = arr + 100

In [11]:
arr_3

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

### Broadcasting into an array, affecting the original array

In [12]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
slice_of_arr = arr[0:5]

In [18]:
slice_of_arr [:] = 99

In [19]:
slice_of_arr

array([99, 99, 99, 99, 99])

the above has affected the original arry as the slice is pointing to the original array

In [21]:
arr ## see it affected the original array, so be careful while broadcasting values

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9])

To avoid this we have to exclusively create a copy of the array by using the copy function

In [23]:
arr_copy = arr.copy()

In [24]:
arr_copy 

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9])

In [25]:
arr_copy[:] = 1000

In [26]:
arr_copy

array([1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [28]:
arr # this way we don't affect the original array

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9])

Indexing and Selection on a 2 D array / Matrix

In [30]:
arr_2d = np.array([[2,3,4],[4,5,3],[2,3,3]])

In [31]:
arr_2d

array([[2, 3, 4],
       [4, 5, 3],
       [2, 3, 3]])

In [32]:
arr_2d.shape

(3, 3)

In terms of matrix/ 2 D array - the indexes refers to the row

In [36]:
arr_2d[1] # first row but in python as we remember indexing starts at 0

array([4, 5, 3])

In [37]:
arr_2d[1][1]

5

In [39]:
arr_2d[1,1] # both gives the same result

5

In [40]:
arr_2d[2,2]

3