#### NUMPY

Numpy Arrays

In [3]:
import numpy as np

In [4]:
mylist = [1,2,3,4]

In [5]:
np.array(mylist)

array([1, 2, 3, 4])

In [7]:
arr = np.array(mylist) ## creating an object

transforming a nested list into a numpy array which will be a matrix

In [8]:
mylist2 = [[1,2,3], [4,5,6], [7,8,9]]

In [11]:
mylist2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
mylist_arr = np.array(mylist2)

In [13]:
mylist_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
mylist_arr.shape


(3, 3)

In [15]:
np.arange(0,20,2), ## not including the last one

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [19]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [20]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
np.ones((5,5))+5 ## can't be done in normal python list, only in numpy

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [24]:
np.ones(4) * 100 ## will multiply each element with 100 but in normal python list -- 

array([100., 100., 100., 100.])

In [26]:
[1,2,3,4] * 3 ## repeats the elemts three elements rather than multiplying the elements with 3

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [28]:
[1,2,1,4] + 10 ## python list interprets as different datatypes not as an arithematic operation as in the case of numpy

TypeError: can only concatenate list (not "int") to list

In [34]:
linspce = np.linspace(0,20,10) ## evenly spaced numbers with step size 10

In [35]:
len(linspce)

10

In [37]:
np.eye(5) ## gives identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [43]:
np.random.rand(1) ## chooses random number between 0 and 1 and it's uniform distribution

array([0.97454151])

In [45]:
np.random.rand(4) ## return 4 random numbers between 0 and 1

array([0.44372381, 0.85754049, 0.42784277, 0.55924982])

In [51]:
np.random.rand(5,5) ## returns a matrix of random numebers

array([[0.16623468, 0.23599617, 0.71373439, 0.93125663, 0.51373057],
       [0.21479798, 0.74541366, 0.30230789, 0.09582425, 0.3673805 ],
       [0.02936196, 0.37758576, 0.24249469, 0.89855094, 0.66357028],
       [0.4608126 , 0.86243922, 0.59877386, 0.72083443, 0.31780011],
       [0.41994932, 0.03348362, 0.47238255, 0.2273176 , 0.94873416]])

In [52]:
np.random.randn(10) ## return standard normal distribution (SND - mean at 0 and Standard deviation of 1)

array([-1.03384992,  0.43232331,  0.33983793, -0.23578104, -0.37240924,
        0.28476532,  0.60591282,  0.52402607,  0.9006812 , -0.31980863])

In [53]:
np.random.normal() ## if you want to define your own mean and sigma, loc - mean , and scale - sigma / standard deviation

-0.6018318945436868

In [54]:
np.random.randint(1,100,10)

array([26, 83, 77, 81, 39, 68, 36, 65, 86, 25])

In [57]:
np.random.seed(42) ## to have the same set of random numbers as other person , these both needs to be in the same column
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [58]:
arr1 = np.arange(25)

In [59]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [61]:
arr1.reshape(5,5) #3 reshaping into two dimensions

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [63]:
arr1.max()

24

In [65]:
arr1.min()

0

In [66]:
arr1.argmax() ## location of the maximum value in the array

24

In [67]:
arr1.argmin() ## location of the minimum value in the array

0